language: python

notifications:
  email: false

python:
- '2.7'
- '3.4'
- '3.5'

before_install:
- which python
- python --version

install:
- pip install numpy
- pip install pytest pytest-cov
- pip freeze
- git clone https://github.com/cimatosa/progress.git progress_package
- ln -s progress_package/progress
- git clone https://github.com/cimatosa/binfootprint.git binfootprint_package
- ln -s binfootprint_package/binfootprint

script:
- py.test tests/ -v --cov=persistentdata --cov-report term-missing

after_success:
- bash <(curl -s https://codecov.io/bash)
